# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  myLapTop

steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'specific'
      project: '488af890-9aa3-402a-8504-fef1877567b7'
      pipeline: '1'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      allowPartiallySucceededBuilds: true
      downloadType: 'single'
      artifactName: 'angularAppTestArtifacts'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureWebApp@1 
    inputs:
      azureSubscription: 'Azure subscription 1(0ea2ee0e-54d2-4fb8-ab64-cd4250597f0d)'
      appType: 'webAppLinux'
      appName: 'anotherAngularTest'
      deployToSlotOrASE: true
      resourceGroupName: 'anotherAngularTest_group'
      slotName: 'production'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      runtimeStack: 'NODE|20-lts'