# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# azure-pipelines.yml
# npm install Install project dependencies
# npm run build Run your build script (if applicable)

trigger:
  - main # Trigger the pipeline on pushes to the main branch

pool:
  myLapTop # Use a Linux agent for building

variables:
  appName: 'anotherAngularTest' # Name of your Azure App Service
  azureSubscription: 'Azure subscription 1(0ea2ee0e-54d2-4fb8-ab64-cd4250597f0d)' # Name of your Azure service connection

stages:
- stage: Build
  displayName: Build Node.js Application
  jobs:
  - job: BuildJob
    displayName: Build and Package
    steps:
    - task: NodeTool@0
      displayName: 'Use Node.js 20.x'
      inputs:
        versionSpec: '20.x' # Specify the Node.js version

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'Install dependencies and Build'

    - task: ArchiveFiles@2
      displayName: 'Archive Application Files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
      artifact: 'myWebApp'
      displayName: 'Publish Build Artifact'

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build # This stage depends on the successful completion of the Build stage
  jobs:
  - job: DeployJob
    displayName: Deploy Application
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(appName)'
        package: '$(Pipeline.Workspace)/$(appName).zip' # Path to the published artifact
        appType: 'webAppLinux' # Specify 'webAppLinux' for Linux-based App Service
